### ISSUE TITLE
calibreMetadata: Make sure to start Content Server error

### ISSUE THREAD

**Issue by VictorVow** [duydl/logseq-calibre-metadata#3]
I can see my Calibre library through a web browser at http://localhost:3296/#library_id=Calibre-Library&panel=book_list.

In the plugin settings I changed the Preferred Calibre Library to `Calibre-Library` and Content Server Link to http://localhost:3296.

Despite this when I use the `Calibre: Add a Calibre book` command in Logseq when I begin typing to search for a book title it shows the error `calibreMetadata: Make sure to start Content Server.` and is never able to show any books.

**Comment by VictorVow** [comment]
I disabled the username and password requirement on the content server as I realised there's no way to enter username and password into the plugin. Could this be supported in the future, because it's needed for some features like last read position/annotation syncing apparently.

Unfortunately even disabling this wasn't sufficient as I still got this error and the books still wouldn't show in the search: 
![image](https://github.com/duydl/logseq-calibre-metadata/assets/12621257/e6fb9887-4a87-4e0e-8be9-e2b83612b2db)

**Comment by duydl** [comment]
When I enabled the password requirement I did get your error. However, when I disabled the password, the problem was gone. Could you try it again? Perhaps you didn't stop and start the server manually after clicking Apply. Actually clicking Apply is not needed at all. I just unchecked the require username and password, box stop and start the server. Then I was able to add books again. 

I am looking at the Calibre API and there doesn't seem to be a function to login from iframe. In any case, I will work on the Calibre API if it is necessary.

**Comment by VictorVow** [comment]
Ah you're right that was silly of me, yup restarting it made it work. Thanks for the help!
