### ISSUE TITLE
'Request to Calibre Server failed'

### ISSUE THREAD

**Issue by bartart3d** [duydl/logseq-calibre-metadata#5]
Hello,

I first posted this on the annotation plugin, should be here:

I constantly get 'Request to Calibre Server failed'

Server is up and running though, tested it by pressing 'test server'. It runs perfectly on port 9090

url's I tried are: http://localhost:9090/, http://127.0.0.1:9090/

The location of the calibre library is on a sshfs mounted network drive, so the location points to a mounted directory. Could that be the issue?

**Comment by duydl** [comment]
What is the url when opened in browser when you pressed "test server"? You should use that URL. Instead of 127.0.0.1 i.e localhost, try the content server domain for local network, the one shown here: 
![image](https://github.com/duydl/logseq-calibre-metadata/assets/56506156/123b4a52-8cea-4d2d-ba54-b201245753c4)

Also, do not add the extra "/" in the URL as it sometimes results in error.

**Comment by bartart3d** [comment]
Hello,

- When testing the server, it shows 127.0.0:8081 as URL.
- I tried with localhost and above IP, with and without slashes, without effect.
- In the settings in calibre the IP shows as 192.1.168.10:8081, when entering that as url in the addons settings, I get the same result: Request to Calibre Content Server failed.
- Testing further, when I deliberately enter a wrong IP, it gives a different error: Make sure to start the Content Server'.

It looks to me that, with the correct IP Calibre Server is reached, but the plugin is not allowed to read from it. 

I used to have user account for the calibre server, which I disabled and removed, after which I did restart the server

Further info: logseq installation is from a flatpack package, I uninstalled, tried it with a snap package, same error. The AppImage provided on the website gives the same result.
Calibre is installed with the command shown on their website, now version 7.1.0.

**Comment by duydl** [comment]
Apologize for the late reply. 
'Request to Calibre Server failed' is usually because of user account setup in Calibre server. 
After you restart the server sometimes due to cache problem the plugin is still unable to connect. 

- If you have installed the annotation plugin, could y try pasting this macro: 
`{{renderer calibreViewer, special, http://192.168.11.2:8081}}` (change to your link)
and open the rendered button. If the server opened on the right side like on the browser, then you could still use the annotation plugin to read and annotate book.

**Comment by bartart3d** [comment]
Hello,

thanks for the workaround, this seems to work :-)

**Comment by chris-lis** [comment]
Hey, I run into this issue as well, but managed to solve it: it turns out that when you have a space in the library name, Calibre Server replaces it with an underscore to create the library ID. So, simply changing `Calibre Library` to `Calibre_Library` in the plugin config did the trick & now it works perfectly.

Hope this helps someone. Also, it might be worth adding a disclaimer about it in the Readme & the plugin config.

**Comment by duydl** [comment]
@chris-lis Thank you very much and sorry for the inconvenience. I will add a fix to replace space with _ when parsing the setting.
