### ISSUE TITLE
Does Calibre in docker can sync?

### ISSUE THREAD

**Issue by nmuxiang** [duydl/logseq-calibre-metadata#6]
hello, I run calibre in docker, I can open a book in logseq or browser, and I press the button 'sync', but when I highlight or annotation in logseq or browser, it can't sync to logseq. What should I do?

**Comment by duydl** [comment]
um seem strange, it should work as normal. Could you try open the developer console in logseq to see if there any error. 

Also in the meantime, I have added a feature in calibre ebook reader to allow copy annotation into a template. So you could copy a highlight and paste it in logseq and it will generate a corresponding link.
![image](https://github.com/user-attachments/assets/e187e303-0308-4903-ba5e-eeb7824a0715)

**Comment by nmuxiang** [comment]
I open developer console and find the error. Do I have some way to solved it?  
![屏幕截图 2024-07-13 213010](https://github.com/user-attachments/assets/728707e9-860a-4bf3-ae71-a24f111780af)

**Comment by duydl** [comment]
Sorry for late reply. With the new version, try enabling authen login with username and password in Content Server and fill in the corresponding setting in Logseq.
If the problem persists, please create new issue https://github.com/duydl/logseq-calibre-annotation/issues since I migrated all functionalities of this plugin there.
